BankingApplication/BankingApplication/Models/Card.cs
using Microsoft.AspNetCore.Identity;

namespace BankingApplication.Models;

public class Card
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string CardNumber { get; set; }

    public DateTime ExpirationDate { get; set; }

    public int CVV { get; set; }

    public IdentityUser User { get; set; }

    public bool IsLocked { get; set; }

    public Card()
    {
        
    }

    public Card(int Id, IdentityUser User)
    {
        this.Id = Id;
        this.User = User;
    }
}

BankingApplication/BankingApplication/Controllers/CardsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BankingApplication.Models;
using BankingApplication.Services.Interfaces;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace BankingApplication.Controllers
{
    [Authorize]
    public class CardsController : Controller
    {
        private readonly ICardService _cardService;
        private readonly UserManager<IdentityUser> _userManager;

        public CardsController(ICardService cardService, UserManager<IdentityUser> userManager)
        {
            _cardService = cardService;
            _userManager = userManager;
        }

        // GET: Cards
        public async Task<IActionResult> Index()
        {
              var cards= _cardService.GetCards();
              return View(cards);
        }

        // GET: Cards/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var card = _cardService.GetCardById(id);
            if (card == null)
            {
                return NotFound();
            }

            return View(card);
        }

        // GET: Cards/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cards/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,CardNumber,ExpirationDate,CVV,IsLocked")] Card card)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = await _userManager.FindByIdAsync(userId);
            card.User = user;
            _cardService.Create(card);
                return RedirectToAction(nameof(Index));

            return View(card);
        }

        // GET: Cards/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var card = _cardService.GetCardById(id);
            if (card == null)
            {
                return NotFound();
            }
            return View(card);
        }

        // POST: Cards/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,CardNumber,ExpirationDate,CVV,IsLocked")] Card card)
        {
            if (id != card.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                   _cardService.Update(card);
                }
                catch (DbUpdateConcurrencyException)
                {
                   
                    throw;

                }
                return RedirectToAction(nameof(Index));
            }
            return View(card);
        }

        // GET: Cards/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var card = _cardService.GetCardById(id);
            if (card == null)
            {
                return NotFound();
            }

            return View(card);
        }

        // POST: Cards/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var card = _cardService.GetCardById(id);
            if (card != null)
            {
                _cardService.Delete(id);
            }
           
            return RedirectToAction(nameof(Index));
        }
    }
}

BankingApplication/BankingApplication/Controllers/TransactionsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BankingApplication.Models;
using BankingApplication.Services.Interfaces;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace BankingApplication.Controllers
{
    [Authorize]
    public class TransactionsController : Controller
    {
        private readonly ITransactionService _transactionService;
        private readonly IBankAccountService _bankAccountService;

        public TransactionsController(ITransactionService transactionService, IBankAccountService bankAccountService)
        {
            _transactionService = transactionService;
            _bankAccountService = bankAccountService;
        }

        // GET: Transactions
        public async Task<IActionResult> Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var transactions = _transactionService.GetTransactions(userId);
            for(int i = 0; i < transactions.Count(); i++)
            {
                transactions[i].Reciver = _bankAccountService.GetBankAccountById(transactions[i].ReciverId ?? 0);
                transactions[i].Sender = _bankAccountService.GetBankAccountById(transactions[i].SenderId ?? 0);
            }
            return View(transactions);
        }

        // GET: Transactions/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var transaction = _transactionService.GetTransactionById(id);
            transaction.Reciver = _bankAccountService.GetBankAccountById(transaction.ReciverId ?? 0);
            transaction.Sender = _bankAccountService.GetBankAccountById(transaction.SenderId ?? 0);
            if (transaction == null)
            {
                return NotFound();
            }

            return View(transaction);
        }

        // GET: Transactions/Create
        public IActionResult Create()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            ViewData["ReciverId"] = new SelectList(_bankAccountService.GetBankAccounts(), "Id", "Name");
            ViewData["SenderId"] = new SelectList(_bankAccountService.GetBankAccountsOfUser(userId), "Id", "Name");
            return View();
        }

        // POST: Transactions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Amount,SenderId,ReciverId")] Transaction transaction)
        {
            transaction.Date = DateTime.Now;
            if (ModelState.IsValid)
            {   
                _transactionService.Create(transaction);
                _transactionService.PerformTransaction(transaction.SenderId, transaction.ReciverId, transaction.Amount);
                return RedirectToAction(nameof(Index));
            }
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            ViewData["ReciverId"] = new SelectList(_bankAccountService.GetBankAccounts(), "Id", "Id", transaction.ReciverId);
            ViewData["SenderId"] = new SelectList(_bankAccountService.GetBankAccountsOfUser(userId), "Id", "Name");
            return View(transaction);
        }


        public IActionResult Create1()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            ViewData["ReciverId"] = new SelectList(_bankAccountService.GetBankAccountsThatAreService(), "Id", "Name");
            ViewData["SenderId"] = new SelectList(_bankAccountService.GetBankAccountsOfUser(userId), "Id", "Name");
            return View();
        }

        // POST: Transactions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create1([Bind("Id,Amount,SenderId,ReciverId")] Transaction transaction)
        {
            transaction.Date = DateTime.Now;
            if (ModelState.IsValid)
            {  
                _transactionService.Create(transaction);
                _transactionService.PerformTransaction(transaction.SenderId, transaction.ReciverId, transaction.Amount);
                return RedirectToAction(nameof(Index));
            }
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            ViewData["ReciverId"] = new SelectList(_bankAccountService.GetBankAccountsThatAreService(), "Id", "Id", transaction.ReciverId);
            ViewData["SenderId"] = new SelectList(_bankAccountService.GetBankAccountsOfUser(userId), "Id", "Name");
            return View(transaction);
        }

        // GET: Transactions/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var transaction = _transactionService.GetTransactionById(id);
            if (transaction == null)
            {
                return NotFound();
            }
            ViewData["ReciverId"] = new SelectList(_bankAccountService.GetBankAccounts(), "Id", "Id", transaction.ReciverId);
            ViewData["SenderId"] = new SelectList(_bankAccountService.GetBankAccounts(), "Id", "Id", transaction.SenderId);
            return View(transaction);
        }

        // POST: Transactions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Amount,Date,SenderId,ReciverId")] Transaction transaction)
        {
            if (id != transaction.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _transactionService.Update(transaction);
                }
                catch (DbUpdateConcurrencyException)
                {  
                       throw;
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ReciverId"] = new SelectList(_bankAccountService.GetBankAccounts(), "Id", "Id", transaction.ReciverId);
            ViewData["SenderId"] = new SelectList(_bankAccountService.GetBankAccounts(), "Id", "Id", transaction.SenderId);
            return View(transaction);
        }

        // GET: Transactions/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var transaction = _transactionService.GetTransactionById(id);
            if (transaction == null)
            {
                return NotFound();
            }

            return View(transaction);
        }

        // POST: Transactions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var transaction = _transactionService.GetTransactionById(id);
            if (transaction != null)
            {
                _transactionService.Delete(id);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

BankingApplication/BankingApplication/Views/Cards/Create.cshtml
@model BankingApplication.Models.Card

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Card</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CardNumber" class="control-label"></label>
                <input asp-for="CardNumber" class="form-control" />
                <span asp-validation-for="CardNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExpirationDate" class="control-label"></label>
                <input asp-for="ExpirationDate" class="form-control" />
                <span asp-validation-for="ExpirationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CVV" class="control-label"></label>
                <input asp-for="CVV" class="form-control" />
                <span asp-validation-for="CVV" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsLocked" /> @Html.DisplayNameFor(model => model.IsLocked)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a  class="btn btn-secondary" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BankingApplication/BankingApplication/Views/Cards/Delete.cshtml
@model BankingApplication.Models.Card

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Card</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CardNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CardNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExpirationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExpirationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CVV)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CVV)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsLocked)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsLocked)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BankingApplication/BankingApplication/Views/Cards/Details.cshtml
@model BankingApplication.Models.Card

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Card</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CardNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CardNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExpirationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExpirationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CVV)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CVV)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsLocked)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsLocked)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

BankingApplication/BankingApplication/Views/Cards/Edit.cshtml
@model BankingApplication.Models.Card

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Card</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CardNumber" class="control-label"></label>
                <input asp-for="CardNumber" class="form-control" />
                <span asp-validation-for="CardNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExpirationDate" class="control-label"></label>
                <input asp-for="ExpirationDate" class="form-control" />
                <span asp-validation-for="ExpirationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CVV" class="control-label"></label>
                <input asp-for="CVV" class="form-control" />
                <span asp-validation-for="CVV" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsLocked" /> @Html.DisplayNameFor(model => model.IsLocked)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BankingApplication/BankingApplication/Views/Cards/Index.cshtml
@model IEnumerable<BankingApplication.Models.Card>

@{
    ViewData["Title"] = "Index";
}


<div>
    <meta charset="UTF-8">
    <title>Card Boxes Example</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css" integrity="sha512-RhUSmEFl0H/4M6Bj0/d0s4pG9/4TfT6Nqj3UWeN6Q2zl6CZ8jbvCcL3jIz+cQ9KjPZ8RvPSbRr+IpljlxGRT1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- Custom CSS -->
    <style>
        .container {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }

        /* Style for card-box */
        .card-box {
            width: 400px;
            height: 200px;
            border-radius: 10px;
            padding: 20px;
            margin-top: 20px;
            margin-bottom: 60px;
            /*background-color: #AED6FA;*/
            background-image: linear-gradient(to bottom right, #0B5ED7, #D315B7);
            box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.1);
            position: relative;
        }

        /* Style for card-exp-cvv-box */
        .card-exp-cvv-box {
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .expiry {
            flex: 60%;
        }

        .cvv {
            flex: 40%;
        }

        /* Style for card title */
        .card-title {
            font-size: 24px;
            font-weight: bold;
            color: #ffffff;
            margin-top: 5px;
            margin-bottom: 20px;
        }

        /* Style for card content */
        .card-heading-text {
            font-size: 12px;
            color: #ffffff;
            margin-top: 16px;
            margin-bottom: 2px;
        }

        /* Style for card content */
        .card-text {
            font-size: 16px;
            color: #f0f0f0;
            margin-top: 2px;
            margin-bottom: 16px;
        }


        .circle-button1 {
            width: 60px;
            height: 60px;
            border-radius: 50%;
            border: 2px solid #0d6efd;
            font-size: 12px;
            font-weight: bold;
            color: #ffffff;
            background-color: #0d6efd;
            box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.4);
            text-align: center;
            padding: 10px 0;
            position: absolute;
            left: 430px;
            top: 0px;
        }

        .circle-button2 {
            width: 60px;
            height: 60px;
            border-radius: 50%;
            border: 2px solid #0d6efd;
            font-size: 12px;
            font-weight: bold;
            color: #ffffff;
            background-color: #0d6efd;
            box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.4);
            text-align: center;
            padding: 16px 0;
            position: absolute;
            left: 430px;
            top: 70px;
        }

        .circle-button3 {
            width: 60px;
            height: 60px;
            border-radius: 50%;
            border: 2px solid #0d6efd;
            font-size: 12px;
            font-weight: bold;
            color: #ffffff;
            background-color: #0d6efd;
            box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.4);
            text-align: center;
            padding: 8px 0;
            position: absolute;
            left: 430px;
            top: 140px;
        }

        .circle-button1:hover {
            background-color: #ffffff;
            border: 2px solid #0B5ED7;
        }

        .circle-button2:hover {
            background-color: #ffffff;
            border: 2px solid #0B5ED7;
        }

        .circle-button3:hover {
            background-color: #ffffff;
            border: 2px solid #0B5ED7;
        }

    </style>
</div>

<div>
    <div class="text-center">
        <h1 style="color: #026efd;">
            <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-credit-card-2-back-fill" viewBox="0 0 16 16">
                <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v5H0V4zm11.5 1a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h2a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-2zM0 11v1a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-1H0z" />
            </svg> My Cards
        </h1>
    </div>
    <hr />

    <div class="container">
        @foreach (var item in Model)
        {
            <div class="card-box">
                <h2 class="card-title">@Html.DisplayFor(modelItem => item.Name)</h2>

                <p class="card-heading-text">IBAN</p>
                <p class="card-text">@Html.DisplayFor(modelItem => item.CardNumber)</p>

                <div class="card-exp-cvv-box">
                    <div class="expiry">
                        <p class="card-heading-text">Expiry date</p>
                        <p class="card-text">@Html.Raw(item.ExpirationDate.ToString("MM\\/yy"))</p>
                    </div>
                    <div class="cvv">
                        <p class="card-heading-text">CVV</p>
                        <p class="card-text">@Html.DisplayFor(modelItem => item.CVV)</p>
                    </div>
                </div>              
                <a class="circle-button3" asp-controller="Transactions" asp-action="Index">Trans<br>actions</a>

            </div>
        }
    </div>
</div>